// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygpxlyphryvsnsudgycc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncHhseXBocnl2c25zdWRneWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDA2MTgsImV4cCI6MjA2NDg3NjYxOH0.Bw5RgvR5rpdfsFy-wPJxgyIN1LNb1eIrWLHxDGB5lqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);